import { SharedSceneElements } from './scenes/SharedSceneElements.jsx';
import { sceneRendererKeys } from '../../content/sceneRendererKeys.js';
import { HeroScene } from './scenes/HeroScene.jsx';
import { EvolutionScene } from './scenes/EvolutionScene.jsx';
import { CodexWorkflowScene } from './scenes/CodexWorkflowScene.jsx';
import { PromptSystemScene } from './scenes/PromptSystemScene.jsx';
import { SpecificationScene } from './scenes/SpecificationScene.jsx';
import { ArchitectureScene } from './scenes/ArchitectureScene.jsx';
import { PlanningScene } from './scenes/PlanningScene.jsx'; import { AgentsMdScene } from './scenes/AgentsMdScene.jsx';
import { SkillsScene } from './scenes/SkillsScene.jsx'; import { McpScene } from './scenes/McpScene.jsx';
import { AgentsScene } from './scenes/AgentsScene.jsx';
import { OrchestrationScene } from './scenes/OrchestrationScene.jsx';
import { ImplementationScene } from './scenes/ImplementationScene.jsx';
import { VerificationScene } from './scenes/VerificationScene.jsx';
import { SecurityScene } from './scenes/SecurityScene.jsx';
import { HumanDecisionScene } from './scenes/HumanDecisionScene.jsx';
import { StoryScene } from './scenes/StoryScene.jsx';
void SharedSceneElements;
void HeroScene; void EvolutionScene; void CodexWorkflowScene; void PromptSystemScene; void SpecificationScene; void ArchitectureScene; void PlanningScene; void AgentsMdScene; void SkillsScene; void McpScene; void AgentsScene; void OrchestrationScene; void ImplementationScene; void VerificationScene; void SecurityScene; void HumanDecisionScene;
export const sceneRenderers = { ...Object.fromEntries(sceneRendererKeys.map((key) => [key, SharedSceneElements])), story: StoryScene, hero: HeroScene, timeline: EvolutionScene, workflow: CodexWorkflowScene, 'prompt-system': PromptSystemScene, specification: SpecificationScene, architecture: ArchitectureScene, planning: PlanningScene, 'agents-md': AgentsMdScene, skills: SkillsScene, mcp: McpScene, agents: AgentsScene, orchestration: OrchestrationScene, implementation: ImplementationScene, verification: VerificationScene, security: SecurityScene, 'human-decision': HumanDecisionScene };
